name: .NET CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore (only if a solution exists)
        if: ${{ hashFiles('**/*.sln') != '' }}
        run: dotnet restore
      - name: Build (only if a solution exists)
        if: ${{ hashFiles('**/*.sln') != '' }}
        run: dotnet build --configuration Release --no-restore
      - name: Test (only if tests exist)
        if: ${{ hashFiles('**/*Tests/*.csproj') != '' }}
        run: dotnet test --no-build --verbosity normal
